config/routes.rb
Multidraft::Application.routes.draw do
  resources :drafts, except: [:edit, :update]
  resources :drafters, only: [:create, :destroy]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => 'users/registrations' }
  devise_scope :user do
    delete "remove_authentication/:id" => 'users/registrations#remove_authentication', :as => 'remove_authentication'
  end

  root :to => 'placeholder#index'
  get "new_booster" => 'placeholder#new_booster', as: 'new_booster'
  post "generate_booster" => 'placeholder#generate_booster', as: 'generate_booster'

  get "multiverse_sets" => 'placeholder#setup_multiverse_sets', as: 'multiverse_sets'

end

app/controllers/placeholder_controller.rb
class PlaceholderController < ApplicationController
  include MultiverseInterface

  before_filter :authenticate_user!, except: [:index]

  def index
  end

  def new_booster
  end

  # Read and parse the Multiverse set list, then return JS to
  # set up the drop down.
  def setup_multiverse_sets
    @sets = multiverse_sets.sort_by(&:name)
    render layout: false
  end

  def generate_booster
    if params[:multiverse] == 'false'
      @booster = CardSet.find(params[:id]).generate_booster
    else
      data = JSON.parse(params[:multiverse_data])
      set = CardSet.where { name == data['name'] }.first || CardSet.create(name: data['name'],
                                                                            remote_dictionary: true,
                                                                            dictionary_location: data['uri'])
      @booster = set.generate_booster
    end
    respond_to do |format|
      format.js
      format.html { render :new_booster }
    end
  ensure
    @booster.andand.each(&:destroy)
  end
end

app/views/placeholder/generate_booster.js.erb
$('#booster').empty();
<% @booster.each do |card| %>
  $('#booster').append("<%= j render('shared/card_instance', card: card) -%>");
<% end %>

app/views/placeholder/index.html.slim
= link_to "Generate a booster", new_booster_path

app/views/placeholder/new_booster.html.haml
= form_tag generate_booster_path, remote: true, class: 'gen-booster' do
  %fieldset
    %legend Magic: the Gathering sets
    .fields
      = hidden_field_tag :multiverse, :false
      = select_tag :id, option_groups_from_collection_for_select(CardSet::RealMagicSets, :second, :first, :id, :name)
      = submit_tag 'Generate booster', disable_with: 'Generating...'

= form_tag generate_booster_path, remote: true, class: 'gen-booster' do
  %fieldset
    %legend Multiverse sets
    .fields
      = hidden_field_tag :multiverse, :true
      = text_field_tag :uri, nil, placeholder: 'JSON URL for set', data: { multiverse_select: multiverse_sets_path }
      = submit_tag 'Generate booster', disable_with: 'Generating...'

#booster
  - @booster.andand.each do |card|
    = render('shared/card_instance', card: card)

app/views/placeholder/new_booster.html.slim
= form_tag generate_booster_path, remote: true, class: 'gen-booster' do
  fieldset
    legend Magic: the Gathering sets
    .fields
      = hidden_field_tag :multiverse, :false
      = select_tag(:id, option_groups_from_collection_for_select(CardSet::RealMagicSets, :second, :first, :id, :name))
      = submit_tag 'Generate booster', disable_with: 'Generating...'

= form_tag generate_booster_path, remote: true, class: 'gen-booster' do
  fieldset
    legend Multiverse sets
    .fields
      = hidden_field_tag :multiverse, :true
      = text_field_tag :uri, nil, placeholder: 'JSON URL for set', data: { multiverse_select: multiverse_sets_path }
      = submit_tag 'Generate booster', disable_with: 'Generating...'

#booster
  - @booster.andand.each do |card|
    = render('shared/card_instance', card: card)

app/views/placeholder/setup_multiverse_sets.html.slim
= select_tag :multiverse_data, options_from_collection_for_select(@sets, 'dump', 'descr')