config/routes.rb
Multidraft::Application.routes.draw do
  resources :drafts, except: [:edit, :update]
  resources :drafters, only: [:create, :destroy]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => 'users/registrations' }
  devise_scope :user do
    delete "remove_authentication/:id" => 'users/registrations#remove_authentication', :as => 'remove_authentication'
  end

  root :to => 'placeholder#index'
  get "new_booster" => 'placeholder#new_booster', as: 'new_booster'
  post "generate_booster" => 'placeholder#generate_booster', as: 'generate_booster'

  get "multiverse_sets" => 'placeholder#setup_multiverse_sets', as: 'multiverse_sets'

end

app/models/draft.rb
class Draft < ActiveRecord::Base
  module States
    WAITING = 1
    DRAFTING = 2
    DECK_BUILDING = 3
    ENDED = 4

    AllStates = [WAITING, DRAFTING, DECK_BUILDING, ENDED]
  end

  validates :name, presence: true, uniqueness: true
  validates :state, presence: true, numericality: true, inclusion: { in: States::AllStates }

  has_many :drafters, dependent: :destroy
  has_many :users, -> { uniq }, through: :drafters

  scope :waiting, -> { where(state: States::WAITING) }
  scope :drafting, -> { where(state: States::DRAFTING) }
  scope :building, -> { where(state: States::DECK_BUILDING) }
  scope :running, -> { where(state: [States::DRAFTING, States::DECK_BUILDING])}
  scope :ended, -> { where(state: States::ENDED) }

  scope :without_user, -> (omit_user_id) { where{id.not_in (Drafter.where{(draft_id == drafts.id) & (user_id == omit_user_id)}.select(:draft_id))} }

  before_validation :init_state, on: :create

private
  def init_state
    self.state = States::WAITING
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: [:show, :destroy]
  before_filter :authenticate_user!, except: [:index]
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  respond_to :html

  def index
    @drafts = Draft.all
    respond_with(@drafts)
  end

  def show
    respond_with(@draft)
  end

  def new
    @draft = Draft.new
    respond_with(@draft)
  end

  def create
    @draft = Draft.new(draft_params)
    @draft.save
    respond_with(@draft)
  end

  def destroy
    @draft.destroy
    respond_with(@draft)
  end

  private
    def set_draft
      @draft = Draft.find(params[:id])
    end

    def draft_params
      params.require(:draft).permit(:name)
    end

    def record_not_found
      redirect_to drafts_path, notice: t('drafts.not_found')
    end
end

app/views/drafts/_draft_list.slim
.draft-list
  .list--header= t(".#{type}_count", count: draft_list.count)
  - third_cell_class = {waiting: 'cell--draft-drafters', running: 'cell--draft-state', ended: 'cell--draft-placeholder'}
  - third_cell_fn = {waiting: ->(d){ pluralize(d.drafters.count, 'drafter') },
                      running: ->(d){ t(".states.#{d.state}") },
                      ended: ->(d){ '' }}
  .draft-table
    .table-row.table-header-row
      .table-cell.cell--draft-id Draft #
      .table-cell.cell--draft-name Name
      .table-cell{class=third_cell_class[type]}= t(".third_header.#{type}")

    - draft_list.each do |draft|
      = link_to draft, class: "table-row draft--#{type}" do
        .table-cell.cell--draft-id= draft.id
        .table-cell.cell--draft-name= draft.name
        .table-cell{class=third_cell_class[type]}= third_cell_fn[type].call(draft)

app/views/drafts/index.html.slim
- if @drafts.empty?
  .central-notice
    .notice-text There aren't any drafts at the moment.
    .block-button
      = link_to 'Create one!', new_draft_path, class: 'button'
- else
  - if current_user
    - drafts = current_user.drafts
    .draft-group.user-drafts
      .group--header Your drafts
      - if drafts.empty?
        .left-indent You aren't in any drafts at the moment.
      - if !drafts.waiting.empty?
        = render partial: 'draft_list', object: drafts.waiting, locals: { type: :waiting }

      - if !drafts.running.empty?
        = render partial: 'draft_list', object: drafts.running, locals: { type: :running }

      - if !drafts.ended.empty?
        = render partial: 'draft_list', object: drafts.ended, locals: { type: :ended }

  .draft-group.nonuser-drafts
    - drafts = @drafts
    - if current_user
      .group--header Other drafts
      - drafts = @drafts.without_user(current_user.id)
    - if !drafts.waiting.empty?
      = render partial: 'draft_list', object: drafts.waiting, locals: { type: :waiting }

    - if !drafts.running.empty?
      = render partial: 'draft_list', object: drafts.running, locals: { type: :running }

    - if !drafts.ended.empty?
      = render partial: 'draft_list', object: drafts.ended, locals: { type: :ended }
  br

  = link_to 'New draft', new_draft_path

app/views/drafts/new.html.haml
= form_for @draft do |f|
  - if @draft.errors.any?
    #error_explanation
      %h2= "#{pluralize(@draft.errors.count, "error")} prohibited this draft from being saved:"
      %ul
        - @draft.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    %legend Create a new draft
    .field
      = f.label :name
      = f.text_field :name
    .actions
      = f.submit 'Create'

= link_to 'Back', drafts_path

app/views/drafts/new.html.slim
= form_for @draft do |f|
  - if @draft.errors.any?
    #error_explanation
      h2= "#{pluralize(@draft.errors.count, "error")} prohibited this draft from being saved:"
      ul
        - @draft.errors.full_messages.each do |msg|
          li= msg
  fieldset
    legend Create a new draft
    .field
      = f.label :name
      = f.text_field :name
    .actions
      = f.submit 'Create'

= link_to 'Back', drafts_path

app/views/drafts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @draft.name
%p
  %b State:
  = @draft.state

= link_to 'Back', drafts_path

app/views/drafts/show.html.slim
- content_for :title, @draft.name

h1.draft-name= @draft.name
- in_draft = current_user && @draft.drafters.pluck(:user_id).include?(current_user.id)
- if @draft.drafters.empty?
  .central-notice
    .notice-text There are no drafters in this draft.
    .sub-notice-text Not even the creator...
    - if @draft.state == Draft::States::WAITING && !in_draft
      = form_for(Drafter.new) do |f|
        = f.hidden_field :draft_id, value: @draft.id
        = f.hidden_field :user_id, value: current_user.id
        = f.submit 'Join this draft!'
- else
  table.drafters-list
    thead: tr: th Drafters
    tbody
      - @draft.drafters.each do |drafter|
        tr.row--drafter: td.cell--drafter-name= drafter.user.name
  - if @draft.state == Draft::States::WAITING && !in_draft
    = form_for(Drafter.new) do |f|
      = f.hidden_field :draft_id, value: @draft.id
      = f.hidden_field :user_id, value: current_user.id
      = f.submit 'Join this draft!'

- if in_draft && @draft.state == Draft::States::WAITING
  = button_to 'Leave this draft', drafter_path(@draft.drafters.for_user(current_user.id).first), method: :delete, class: 'danger'

= link_to 'All Drafts', drafts_path